### ISSUE TITLE
Please address me in some small workflows 

### ISSUE THREAD

**Issue by FPSychotic** [naturerobots/mesh_tools#18]
Hi, thanks by these great nodes, really I got impressed by the paper, I think your tools are the starting point to fix so many issues with robotics these days.

I get laser scans with colored pointclouds, and I would like ,apart can use them as you do in your repository (rover), can export the pointcloud+colour+normals,  meshes+colour ,or both to external software as Cloud Compare, Meshlab, blender or Unreal Engine, to in example can make maps for Gazebo, Isaac Sim...

In your paper I read you use HDF5 files but I couldn't find any software that can import them,  could be possible so it in .ASC format maybe?.

Really I think this should be the fact standard, it is so brilliant.

Thanks!

**Comment by aock** [comment]
Hi @FPSychotic,

First of all, thanks for appreciating our work. One workflow I can think of is:

1. Record a map:
    - PCL SLAM, PCL -> Mesh ([lvr2](https://github.com/uos/lvr2), ...)
    - Get it from the architect of your building
    - ...
2. Automatically transport things from A to B in uneven terrain:
    - Localization: [RMCL](https://github.com/uos/rmcl)
    - Path planning and robot control: [mesh_navigation](https://github.com/naturerobots/mesh_navigation) + [move_base_flex](https://github.com/magazino/move_base_flex)

The "how to get a map" is also discussed in issue #20.

After recording a map, you would normally have a standard mesh format such as PLY or OBJ. However, those formats turned out to be not descriptive enough to represent the layered format that we use for navigation. So we agreed on HDF5. Or in more detail, a certain structure within the HDF5 file ([Mesh-Tools Paper](https://kbs.informatik.uos.de/files/pdfs/ras2020_spuetz.pdf), Figure 7). There are also tools such as HDFCompass which you can use to visualize the structure of an already existing H5 file. BTW, the structure looks very similar to a standard file-directory. To convert a standard mesh format (such as PLY) to H5 you can use the lvr2_hdf5_mesh_tool from [lvr2](https://github.com/uos/lvr2).

With migrating everything to ROS2, we are working on providing a set of examples/tutorials/documentation that should address all the old issues that have arisen over the last few years. The issue about the conversion of standard mesh formats to HDF5 is now tracked here #37.

**Comment by amock** [comment]
I think we can close this issue as I integrated most of it in greater detail into the new docs of [mesh_navigation_tutorials](https://github.com/naturerobots/mesh_navigation_tutorials/wiki)
